version: '3'

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dota2bot
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    networks:
      - main
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  node:
    env_file: src/.env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    ports:
      - 1234:1234
    volumes:
      - ./src:/usr/src/app/src
    links:
      - database
    networks:
      - main

networks:
  main:
